n3=input('Digite algo: ')
print('Tipo:', type(n3))
print('É número?',n3.isnumeric())
print('É alfabeto?',n3.isalpha())
print('É decimal?',n3.isdecimal())
print('Está em capslock?',n3.isupper())
print('Só tem espaços? ', n3.isspace())
print('É alfanumérico? ', n3.isalnum())
print('Está capitalizado? ', n3.istitle())